=== aclave1/tgnms/nms_stack/nms_cli/nms_stack/roles/hwprofiles/files/hwprofile-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/terragraph/tgnms/hwprofiles/hwprofile-schema.json",
  "title": "Terragraph NMS Hardware Profile",
  "type": "object",
  "required": [
    "version",
    "hwBoardId",
    "beam_angle_map",
    "tx_power_map",
    "sector_params",
    "financial"
  ],
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "integer",
      "minimum": 0
    },
    "hwBoardId": {
      "type": "string",
      "description": "Hardware Board ID: the primary identifier for a single SKU. This is used to match hardware to hardware profiles."
    },
    "beam_angle_map": {
      "type": "object",
      "description": "Mapping from Tile ID -> Elevation ID -> Beam index -> Beam angle.\nExample: {\"0\":{\"0\":{\"0\":-45,\"1\":-44.25}}",
      "additionalProperties": false,
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "description": "Elevation ID -> Beam index -> Beam angle. Example: {\"0\":{\"0\":-45}}",
          "additionalProperties": false,
          "patternProperties": {
            "^[0-9]+$": {
              "type": "object",
              "additionalProperties": false,
              "patternProperties": {
                "^[0-9]+$": {
                  "type": "number",
                  "description": "Beam angle in degrees"
                }
              },
              "description": "Beam index -> Beam angle mapping. Example: {\"0\":-45}"
            }
          }
        }
      }
    },
    "tx_power_map": {
      "type": "object",
      "description": "Mapping from Channel -> MCS -> tx_power_idx -> tx_power",
      "additionalProperties": false,
      "patternProperties": {
        "(^[0-9]+|default_channel)$": {
          "type": "object",
          "description": "Mapping from MCS -> tx_power_idx -> tx_power",
          "additionalProperties": false,
          "patternProperties": {
            "^([0-9]+|default_mcs)$": {
              "type": "object",
              "description": "Mapping from tx_power_idx -> tx_power",
              "patternProperties": {
                "^[0-9]+$": {
                  "type": "number",
                  "description": "TX Power"
                }
              }
            }
          }
        }
      }
    },
    "topology": {
      "type": "object",
      "required": ["num_sectors_per_box", "max_nodes_per_site", "device_types"],
      "additionalProperties": false,
      "properties": {
        "max_nodes_per_site": {
          "description": "Maximum number of radio boxes allowed on each site",
          "type": "integer"
        },
        "num_sectors_per_box": {
          "type": "integer"
        },
        "device_types": {
          "type": "array",
          "items": {"type": "string", "enum": ["CN", "DN"]}
        }
      }
    },
    "sector_params": {
      "type": "object",
      "description": "Hardware-specific radio parameters, used for planning and analysis",
      "required": [
        "boresite_bw_idx",
        "beam_separate_idx",
        "minimum_snr_db",
        "snr_saturate_thresh_db",
        "max_sidelobe_level_db",
        "min_mcs"
      ],
      "additionalProperties": false,
      "properties": {
        "boresite_bw_idx": {
          "type": "integer",
          "description": "Used by: Scan Service"
        },
        "beam_separate_idx": {
          "type": "integer",
          "description": "Used by: Scan Service"
        },
        "minimum_snr_db": {
          "type": "number",
          "description": "Used by: Scan Service"
        },
        "snr_saturate_thresh_db": {
          "type": "number",
          "description": "Used by: Scan Service"
        },
        "max_sidelobe_level_db": {
          "type": "number",
          "description": "Used by: Scan Service"
        },
        "scan_range_az_deg": {
          "type": "number",
          "description": "Per-sector horizontal beamforming scan range of the antenna in degrees. Used by: Mesh Planner"
        },
        "antenna_boresight_gain_dbi": {
          "type": "number",
          "description": "Antenna gain at boresight (dBi). Used by: Mesh Planner"
        },
        "max_power": {
          "type": "number",
          "description": "Maximum Equivalent/Effective Isotropically Radiated Power in dBm. Used by: Mesh Planner, Scan Service"
        },
        "max_tx_power_dbm": {
          "type": "number",
          "description": "Maximum transmission power in dBm. Used by: Mesh Planner"
        },
        "min_tx_power_dbm": {
          "type": "number",
          "description": "Minimum transmission power in dBm. Used by: Mesh Planner"
        },
        "min_mcs": {
          "type": "integer",
          "description": "Minimum MCS level allowed. Used by: Mesh Planner"
        },
        "tx_diversity_gain_db": {
          "type": "number",
          "description": "Transmitter diversity gain in dB (e.g., polarization diversity). Used by: Mesh Planner"
        },
        "rx_diversity_gain_db": {
          "type": "number",
          "description": "Receiver diversity gain in dB (e.g., polarization diversity). Used by: Mesh Planner"
        },
        "tx_misc_loss_db": {
          "type": "number",
          "description": "Miscellaneous losses on the transmitter in dB (e.g., cable losses). Used by: Mesh Planner"
        },
        "rx_misc_loss_db": {
          "type": "number",
          "description": "Miscellaneous losses on the receiver in dB (e.g., cable losses). Used by: Mesh Planner"
        }
      }
    },
    "financial": {
      "type": "object",
      "required": ["node_capex"],
      "additionalProperties": false,
      "properties": {
        "node_capex": {
          "type": "number",
          "description": "Cost of each individual node. Used by: Mesh Planner"
        }
      }
    }
  }
}

=== aclave1/tgnms/nms_stack/nms_cli/nms_stack/roles/hwprofiles/files/profiles/puma.json
{
  "version": 1,
  "hwBoardId": "NXP_LS1048A_PUMA",
  "tx_power_map": {
    "default_channel": {
      "default_mcs": {
        "0": 19,
        "1": 20,
        "2": 21,
        "3": 22,
        "4": 23,
        "5": 24,
        "6": 25,
        "7": 26,
        "8": 27,
        "9": 28,
        "10": 29,
        "11": 30,
        "12": 31,
        "13": 32,
        "14": 33,
        "15": 34,
        "16": 35,
        "17": 36,
        "18": 37,
        "19": 38,
        "20": 39,
        "21": 40.0,
        "22": 40.5,
        "23": 41.0,
        "24": 41.5,
        "25": 42.0,
        "26": 42.5,
        "27": 43.0,
        "28": 43.5,
        "29": 44.0,
        "30": 44.5,
        "31": 45.0
      }
    }
  },
  "beam_angle_map": {
    "0": {
      "0": {
        "0": -45,
        "1": -44.25,
        "2": -43.5,
        "3": -42.75,
        "4": -42,
        "5": -41.25,
        "6": -40.5,
        "7": -39.75,
        "8": -39,
        "9": -38.25,
        "10": -37.5,
        "11": -36.75,
        "12": -36,
        "13": -35.25,
        "14": -34.5,
        "15": -33.75,
        "16": -33,
        "17": -32.25,
        "18": -31.5,
        "19": -30.75,
        "20": -30,
        "21": -29.25,
        "22": -28.5,
        "23": -27.75,
        "24": -27,
        "25": -26.25,
        "26": -25.5,
        "27": -24.75,
        "28": -24,
        "29": -23.25,
        "30": -22.5,
        "31": -21.75,
        "32": -21,
        "33": -20.25,
        "34": -19.5,
        "35": -18.75,
        "36": -18,
        "37": -17.25,
        "38": -16.5,
        "39": -15.75,
        "40": -15,
        "41": -14.25,
        "42": -13.5,
        "43": -12.75,
        "44": -12,
        "45": -11.25,
        "46": -10.5,
        "47": -9.75,
        "48": -9,
        "49": -8.25,
        "50": -7.5,
        "51": -6.75,
        "52": -6,
        "53": -5.25,
        "54": -4.5,
        "55": -3.75,
        "56": -3,
        "57": -2.25,
        "58": -1.5,
        "59": -0.75,
        "60": 0,
        "61": 0.75,
        "62": 1.5,
        "63": 2.25,
        "64": 3,
        "65": 3.75,
        "66": 4.5,
        "67": 5.25,
        "68": 6,
        "69": 6.75,
        "70": 7.5,
        "71": 8.25,
        "72": 9,
        "73": 9.75,
        "74": 10.5,
        "75": 11.25,
        "76": 12,
        "77": 12.75,
        "78": 13.5,
        "79": 14.25,
        "80": 15,
        "81": 15.75,
        "82": 16.5,
        "83": 17.25,
        "84": 18,
        "85": 18.75,
        "86": 19.5,
        "87": 20.25,
        "88": 21,
        "89": 21.75,
        "90": 22.5,
        "91": 23.25,
        "92": 24,
        "93": 24.75,
        "94": 25.5,
        "95": 26.25,
        "96": 27,
        "97": 27.75,
        "98": 28.5,
        "99": 29.25,
        "100": 30,
        "101": 30.75,
        "102": 31.5,
        "103": 32.25,
        "104": 33,
        "105": 33.75,
        "106": 34.5,
        "107": 35.25,
        "108": 36,
        "109": 36.75,
        "110": 37.5,
        "111": 38.25,
        "112": 39,
        "113": 39.75,
        "114": 40.5,
        "115": 41.25,
        "116": 42,
        "117": 42.75,
        "118": 43.5,
        "119": 44.25
      }
    }
  },
  "topology": {
    "max_nodes_per_site": 1,
    "num_sectors_per_box": 4,
    "device_types": ["CN", "DN"]
  },
  "sector_params": {
    "boresite_bw_idx": 10,
    "minimum_snr_db": -10,
    "snr_saturate_thresh_db": 25,
    "beam_separate_idx": 6,
    "max_sidelobe_level_db": 12,
    "scan_range_az_deg": 90,
    "antenna_boresight_gain_dbi": 30,
    "max_tx_power_dbm": 11,
    "min_tx_power_dbm": -12,
    "min_mcs": 0,
    "tx_diversity_gain_db": 0,
    "rx_diversity_gain_db": 3,
    "tx_misc_loss_db": 7,
    "rx_misc_loss_db": 7
  },
  "financial": {
    "node_capex": 0
  }
}
